"""
macro_simulations.py

Macroeconomic simulation module for the Italian population projection Streamlit app.

Reads all required data from the 'macro/' subfolder generated by extract_macro_data.R:
  macro/df_output.csv
  macro/df_debt.csv
  macro/mod_*_coef.csv   (9 model coefficient files)
  macro/resid_*.csv      (9 residual matrices, 25 rows = 2000-2024 window)

Cross-country interest-rate chain: US → Germany → peripheral countries
(France, Italy, Netherlands, Spain).

Simulation is vectorised across Monte Carlo paths; only the year loop is sequential.
"""

from __future__ import annotations

import os
import warnings
from typing import Dict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

COUNTRY_ORDER = ["US", "Germany", "France", "Italy", "Netherlands", "Spain"]
PERIPHERAL    = ["France", "Italy", "Netherlands", "Spain"]
LARGE_FIGSIZE = (13.5, 7.4)
SCENARIO_COLORS = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"]

VAR_LABELS = {
    "dy":           "Real GDP Growth Rate",
    "g":            "Nominal Growth Rate",
    "pi":           "Inflation",
    "ir":           "Nominal Cost of Debt",
    "b":            "Debt-to-GDP Ratio",
    "s":            "Primary Surplus (% GDP)",
    "s_social":     "Social Surplus (% GDP)",
    "s_non_social": "Non-Social Surplus (% GDP)",
    "ygap":         "Output Gap",
}


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _macro_dir(rdata_path: str) -> str:
    """Return the macro/ subfolder next to rdata_path."""
    return os.path.join(os.path.dirname(os.path.abspath(rdata_path)), "macro")


def _require_macro_dir(macro_dir: str) -> None:
    if not os.path.isdir(macro_dir):
        raise FileNotFoundError(
            f"macro/ folder not found at {macro_dir}.\n"
            "Run extract_macro_data.R once in R/RStudio to generate it."
        )


def load_macro_data(rdata_path: str) -> pd.DataFrame:
    """
    Load df_output.csv and df_debt.csv from the macro/ subfolder, merge them,
    fill PTR_US, and return df_proj filtered to Year > 1970.

    Pre-requisite: run extract_macro_data.R once to populate macro/.
    """
    macro_dir = _macro_dir(rdata_path)
    _require_macro_dir(macro_dir)

    df_output = pd.read_csv(os.path.join(macro_dir, "df_output.csv"))
    df_debt   = pd.read_csv(os.path.join(macro_dir, "df_debt.csv"))

    df_proj = pd.merge(df_output, df_debt, on="Year", how="left", suffixes=("", "_debt"))

    if "PTR_US" in df_proj.columns:
        df_proj["PTR_US"] = df_proj["PTR_US"].ffill().bfill()

    sfa_cols = [c for c in df_proj.columns if c.lower().startswith("sfa_")]
    for col in sfa_cols:
        df_proj.loc[df_proj["Year"] > 2024, col] = 0.0

    df_proj = df_proj[df_proj["Year"] > 1970].reset_index(drop=True)
    return df_proj


def _load_coefs(macro_dir: str, model_name: str) -> Dict[str, float]:
    """Load coefficient CSV → dict {coefficient_name: value}."""
    path = os.path.join(macro_dir, f"{model_name}_coef.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing coefficient file: {path}")
    df = pd.read_csv(path)
    return dict(zip(df["coefficient"], df["value"].astype(float)))


def _load_resid(macro_dir: str, name: str) -> np.ndarray:
    """Load resid_<name>.csv → numpy array (25 rows × n_countries).
    The 'year' column is dropped; remaining columns are residuals."""
    path = os.path.join(macro_dir, f"resid_{name}.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing residual file: {path}")
    df = pd.read_csv(path)
    if "year" in df.columns:
        df = df.drop(columns=["year"])
    arr = df.values.astype(float)
    # Replace NaN with 0 so the simulation always runs
    arr = np.where(np.isnan(arr), 0.0, arr)
    return arr  # shape: (25, n_cols)


def load_model_data(rdata_path: str) -> Dict[str, object]:
    """
    Load all model coefficients and residuals from macro/ CSV files.

    Returns a dict with keys:
        coefs_dypot, coefs_y, coefs_pi_US, coefs_pi, coef_r_US, coef_r_DE,
        coefs_r, coefs_s_social, coefs_s_non_social,
        resid_dypot, resid_y, resid_pi_US, resid_pi, resid_r_US, resid_r_DE,
        resid_r, resid_s_social, resid_s_non_social
    """
    macro_dir = _macro_dir(rdata_path)
    _require_macro_dir(macro_dir)

    return {
        # Coefficients
        "coefs_dypot":       _load_coefs(macro_dir, "mod_dypot_restricted_OLS"),
        "coefs_y":           _load_coefs(macro_dir, "mod_y_restricted_OLS"),
        "coefs_pi_US":       _load_coefs(macro_dir, "mod_pi_US"),
        "coefs_pi":          _load_coefs(macro_dir, "mod_pi_restricted"),
        "coef_r_US":         _load_coefs(macro_dir, "mod_r_US"),
        "coef_r_DE":         _load_coefs(macro_dir, "mod_r_DE"),
        "coefs_r":           _load_coefs(macro_dir, "mod_r_restricted_OLS"),
        "coefs_s_social":    _load_coefs(macro_dir, "mod_s_social"),
        "coefs_s_non_social":_load_coefs(macro_dir, "mod_s_non_social"),
        # Residuals (25 × n_countries arrays)
        "resid_dypot":       _load_resid(macro_dir, "dypot"),
        "resid_y":           _load_resid(macro_dir, "y"),
        "resid_pi_US":       _load_resid(macro_dir, "pi_US"),
        "resid_pi":          _load_resid(macro_dir, "pi"),
        "resid_r_US":        _load_resid(macro_dir, "r_US"),
        "resid_r_DE":        _load_resid(macro_dir, "r_DE"),
        "resid_r":           _load_resid(macro_dir, "r"),
        "resid_s_social":    _load_resid(macro_dir, "s_social"),
        "resid_s_non_social":_load_resid(macro_dir, "s_non_social"),
    }


# ---------------------------------------------------------------------------
# Demographic ratio computation from population projection
# ---------------------------------------------------------------------------

def compute_demo_ratios_from_projection(
    population_by_age_mean: pd.DataFrame,
) -> Dict[str, pd.DataFrame]:
    """
    From population_by_age_mean (output of the demographic projection),
    compute the macro-relevant demographic variables for Italy per scenario.

    Returns {scenario_label: DataFrame(year, N_Y, N_M1, N_M2, N_R, N,
                                       MY, YM, D, D_Y, D_R, n, dn)}.
    """
    pop = population_by_age_mean.copy()
    grouped = pop.groupby(["scenario", "year", "age"])["population"].sum().reset_index()

    results: Dict[str, pd.DataFrame] = {}

    for scenario, sdf in grouped.groupby("scenario"):
        rows = []
        for year, ydf in sdf.groupby("year"):
            ages = ydf["age"].values
            pops = ydf["population"].values

            N_Y  = pops[ages < 20].sum()
            N_M1 = pops[(ages >= 20) & (ages < 45)].sum()
            N_M2 = pops[(ages >= 45) & (ages < 65)].sum()
            N_R  = pops[ages >= 65].sum()
            N    = N_Y + N_M1 + N_M2 + N_R
            denom = N_M1 + N_M2 if (N_M1 + N_M2) > 0 else np.nan

            rows.append({
                "year": year,
                "N_Y": N_Y, "N_M1": N_M1, "N_M2": N_M2, "N_R": N_R, "N": N,
                "MY":  N_M2 / N_M1 if N_M1 > 0 else np.nan,
                "YM":  N_M1 / N_M2 if N_M2 > 0 else np.nan,
                "D":   (N_Y + N_R) / denom if denom else np.nan,
                "D_Y": N_Y / denom          if denom else np.nan,
                "D_R": N_R / denom          if denom else np.nan,
                "n":   np.log(N)             if N > 0 else np.nan,
            })

        df_s = pd.DataFrame(rows).sort_values("year").reset_index(drop=True)
        df_s["dn"] = df_s["n"].diff()
        results[scenario] = df_s

    return results


# ---------------------------------------------------------------------------
# Monte Carlo simulation
# ---------------------------------------------------------------------------

def run_macro_simulations(
    df_proj: pd.DataFrame,
    italy_demo_by_scenario: Dict[str, pd.DataFrame],
    model_data: Dict[str, object],
    num_sim: int = 300,
    curr_year: int = 2024,
) -> Dict[str, Dict[str, pd.DataFrame]]:
    """
    Run the 6-country macroeconomic Monte Carlo simulation for each demographic
    scenario. Italy's demographic variables come from italy_demo_by_scenario;
    all other countries use df_proj values (from estimations.RData).

    model_data: output of load_model_data().

    Returns {scenario_label: {variable_name: DataFrame(year, mean, lower, upper)}}.
    Variables: dy, g, pi, ir, b, s, s_social, s_non_social, snowball, ygap.
    """
    # Unpack coefficients
    COEFS_DYPOT       = model_data["coefs_dypot"]
    COEFS_Y           = model_data["coefs_y"]
    COEFS_PI_US       = model_data["coefs_pi_US"]
    COEFS_PI          = model_data["coefs_pi"]
    COEF_R_US         = model_data["coef_r_US"]
    COEF_R_DE         = model_data["coef_r_DE"]
    COEFS_R           = model_data["coefs_r"]
    COEFS_S_SOCIAL    = model_data["coefs_s_social"]
    COEFS_S_NON_SOCIAL= model_data["coefs_s_non_social"]

    # Unpack residuals (25 × n_cols arrays)
    R_DYPOT    = model_data["resid_dypot"]      # (25, 6)
    R_Y        = model_data["resid_y"]          # (25, 6)
    R_PI_US    = model_data["resid_pi_US"].ravel()  # (25,)
    R_PI       = model_data["resid_pi"]         # (25, 5) non-US
    R_R_US     = model_data["resid_r_US"].ravel()   # (25,)
    R_R_DE     = model_data["resid_r_DE"].ravel()   # (25,)
    R_R        = model_data["resid_r"]          # (25, 4) peripheral
    R_S_SOC    = model_data["resid_s_social"]   # (25, 6)
    R_S_NS     = model_data["resid_s_non_social"]   # (25, 6)

    # Country-index helpers
    def _cidx(country, lst=COUNTRY_ORDER):
        return lst.index(country)

    # Projection rows
    curr_row = df_proj.index[df_proj["Year"] == curr_year]
    if len(curr_row) == 0:
        raise ValueError(f"curr_year={curr_year} not found in df_proj.")
    curr_idx  = curr_row[0]
    proj_df   = df_proj.iloc[curr_idx + 1:].reset_index(drop=True)
    proj_years = proj_df["Year"].values.astype(int)
    n_proj    = len(proj_df)

    if n_proj == 0:
        raise ValueError("No projection rows after curr_year in df_proj.")

    n_resid = R_DYPOT.shape[0]   # 25
    rng = np.random.default_rng()
    sample_idx = rng.integers(0, n_resid, size=(n_proj, num_sim))  # (n_proj, num_sim)

    def _init(col: str) -> float:
        row = df_proj[df_proj["Year"] == curr_year]
        if col in row.columns:
            v = row[col].iloc[0]
            return float(v) if pd.notna(v) else 0.0
        return 0.0

    def _proj_val(col: str, i: int) -> float:
        if col in proj_df.columns:
            v = proj_df[col].iloc[i]
            return float(v) if pd.notna(v) else 0.0
        return 0.0

    # Map residual column names → indices for panel models
    # (column names in the CSV may be "Germany", "Italy", ... or "France_ygap_Italy", etc.)
    def _build_col_idx(arr: np.ndarray, candidates: list) -> Dict[str, int]:
        """Find which column of arr corresponds to each country name."""
        # The R residual matrix uses country names as colnames
        return {c: j for j, c in enumerate(candidates) if j < arr.shape[1]}

    # For panel residuals from systemfit, columns match COUNTRY_ORDER (6 cols)
    # For peripheral spread model, columns match PERIPHERAL (4 cols)
    dypot_cidx = _build_col_idx(R_DYPOT, COUNTRY_ORDER)
    y_cidx     = _build_col_idx(R_Y, COUNTRY_ORDER)
    pi_cidx    = _build_col_idx(R_PI, COUNTRY_ORDER[1:])   # non-US
    r_cidx     = _build_col_idx(R_R, PERIPHERAL)
    ss_cidx    = _build_col_idx(R_S_SOC, COUNTRY_ORDER)
    sns_cidx   = _build_col_idx(R_S_NS, COUNTRY_ORDER)

    all_results: Dict[str, Dict[str, pd.DataFrame]] = {}

    for scenario, italy_demo in italy_demo_by_scenario.items():
        italy_by_year = italy_demo.set_index("year")

        italy_out: Dict[str, np.ndarray] = {k: np.zeros((n_proj, num_sim))
                                             for k in VAR_LABELS}

        # Cross-country linkage arrays
        ir_mat_US      = np.zeros((n_proj, num_sim))
        pi_mat_US      = np.zeros((n_proj, num_sim))
        ir_mat_Germany = np.zeros((n_proj, num_sim))
        b_mat_Germany  = np.zeros((n_proj, num_sim))

        for c in COUNTRY_ORDER:
            # Running lags as (num_sim,) arrays
            y_lag_v    = np.full(num_sim, _init(f"y_{c}"))
            ypot_lag_v = np.full(num_sim, _init(f"ypot_{c}"))
            ygap_lag_v = np.full(num_sim, _init(f"ygap_{c}"))
            pi_lag_v   = np.full(num_sim, _init(f"pi_{c}"))
            ir_lag_v   = np.full(num_sim, _init(f"IR_{c}"))
            b_lag_v    = np.full(num_sim, _init(f"b_{c}"))
            b_de_init  = _init("b_Germany")

            dypot_mat    = np.zeros((n_proj, num_sim))
            dy_mat       = np.zeros((n_proj, num_sim))
            y_mat        = np.zeros((n_proj, num_sim))
            ypot_mat     = np.zeros((n_proj, num_sim))
            ygap_mat     = np.zeros((n_proj, num_sim))
            pi_mat       = np.zeros((n_proj, num_sim))
            ir_mat_c     = np.zeros((n_proj, num_sim))
            s_social_mat = np.zeros((n_proj, num_sim))
            s_ns_mat     = np.zeros((n_proj, num_sim))
            s_mat_c      = np.zeros((n_proj, num_sim))
            b_mat_c      = np.zeros((n_proj, num_sim))
            snowball_mat = np.zeros((n_proj, num_sim))

            for i in range(n_proj):
                year = proj_years[i]
                si   = sample_idx[i]  # (num_sim,) row-indices into resid arrays

                # --- Residual draws (shape: (num_sim,)) ---
                e_dypot = R_DYPOT[si, dypot_cidx.get(c, 0)]
                e_y     = R_Y[si, y_cidx.get(c, 0)]
                e_ss    = R_S_SOC[si, ss_cidx.get(c, 0)]
                e_sns   = R_S_NS[si, sns_cidx.get(c, 0)]

                # --- Demographic variables ---
                if c == "Italy":
                    row_d = italy_by_year.loc[year] if year in italy_by_year.index else italy_by_year.iloc[-1]
                    dn_c  = float(row_d["dn"])  if pd.notna(row_d["dn"])  else 0.0
                    YM_c  = float(row_d["YM"])  if pd.notna(row_d["YM"])  else 0.0
                    D_R_c = float(row_d["D_R"]) if pd.notna(row_d["D_R"]) else 0.0
                    D_c   = float(row_d["D"])   if pd.notna(row_d["D"])   else 0.0
                    MY_c  = float(row_d["MY"])  if pd.notna(row_d["MY"])  else 0.0
                else:
                    dn_c  = _proj_val(f"dn_{c}",  i)
                    YM_c  = _proj_val(f"YM_{c}",  i)
                    D_R_c = _proj_val(f"D_R_{c}", i)
                    D_c   = _proj_val(f"D_{c}",   i)
                    MY_c  = _proj_val(f"MY_{c}",  i)

                # --- Growth ---
                dypot_mat[i] = (COEFS_DYPOT.get(f"{c}_dn_{c}", 0)  * dn_c
                                + COEFS_DYPOT.get(f"{c}_YM_{c}", 0)  * YM_c
                                + COEFS_DYPOT.get(f"{c}_D_R_{c}", 0) * D_R_c
                                + e_dypot)

                dy_mat[i] = (COEFS_Y.get(f"{c}_dypot_{c}", 0)    * dypot_mat[i]
                             + COEFS_Y.get(f"{c}_ygap_lag_{c}", 0) * ygap_lag_v
                             + COEFS_Y.get(f"{c}_D_{c}", 0)         * D_c
                             + e_y)

                y_mat[i]    = y_lag_v    + dy_mat[i]
                ypot_mat[i] = ypot_lag_v + dypot_mat[i]
                ygap_mat[i] = y_mat[i] - ypot_mat[i]

                # --- Inflation & interest rate ---
                if c == "US":
                    PTR_US = _proj_val("PTR_US", i) or 0.02
                    e_pi_US = R_PI_US[si]
                    e_r_US  = R_R_US[si]

                    pi_mat[i] = (COEFS_PI_US.get("pi_lag_US", 0) * pi_lag_v
                                 + COEFS_PI_US.get("PTR_US", 0)   * PTR_US
                                 + e_pi_US)

                    ir_mat_c[i] = (COEF_R_US.get("(Intercept)", 0)
                                   + COEF_R_US.get("dypot_US", 0) * dypot_mat[i]
                                   + COEF_R_US.get("PTR_US", 0)   * PTR_US
                                   + COEF_R_US.get("MY_US", 0)    * MY_c
                                   + e_r_US)

                    ir_mat_US[i] = ir_mat_c[i]
                    pi_mat_US[i] = pi_mat[i]

                elif c == "Germany":
                    j_pi  = pi_cidx.get(c, 0)
                    e_pi  = R_PI[si, j_pi]
                    e_rDE = R_R_DE[si]

                    pi_mat[i] = (COEFS_PI.get(f"{c}_pi_lag_{c}", 0) * pi_lag_v
                                 + COEFS_PI.get(f"{c}_pi_US", 0)     * pi_mat_US[i]
                                 + e_pi)

                    ir_mat_c[i] = (COEF_R_DE.get("(Intercept)", 0)
                                   + COEF_R_DE.get("IR_US", 0)          * ir_mat_US[i]
                                   + COEF_R_DE.get("lag_IR_Germany", 0)  * ir_lag_v
                                   + e_rDE)

                    ir_mat_Germany[i] = ir_mat_c[i]

                else:  # peripheral
                    j_pi  = pi_cidx.get(c, 0)
                    j_r   = r_cidx.get(c, 0)
                    e_pi  = R_PI[si, j_pi]
                    e_r   = R_R[si, j_r]

                    pi_mat[i] = (COEFS_PI.get(f"{c}_pi_lag_{c}", 0) * pi_lag_v
                                 + COEFS_PI.get(f"{c}_pi_US", 0)     * pi_mat_US[i]
                                 + e_pi)

                    b_diff_lag = b_lag_v - (b_de_init if i == 0 else b_mat_Germany[i - 1])
                    spread = (COEFS_R.get(f"{c}_(Intercept)", 0)
                              + COEFS_R.get(f"{c}_b_diff_lag_{c}", 0) * b_diff_lag
                              + e_r)
                    ir_mat_c[i] = spread + ir_mat_Germany[i]

                # --- Fiscal surplus ---
                s_social_mat[i] = (COEFS_S_SOCIAL.get(f"{c}_(Intercept)", 0)
                                   + COEFS_S_SOCIAL.get(f"{c}_ygap_{c}", 0) * ygap_mat[i]
                                   + COEFS_S_SOCIAL.get(f"{c}_D_R_{c}", 0)  * D_R_c
                                   + e_ss)

                s_ns_mat[i] = (COEFS_S_NON_SOCIAL.get(f"{c}_(Intercept)", 0)
                               + COEFS_S_NON_SOCIAL.get(f"{c}_ygap_{c}", 0)  * ygap_mat[i]
                               + COEFS_S_NON_SOCIAL.get(f"{c}_b_lag_{c}", 0) * b_lag_v
                               + e_sns)

                s_mat_c[i] = s_social_mat[i] + s_ns_mat[i]

                # --- Debt dynamics ---
                g_nom       = dy_mat[i] + pi_mat[i]
                b_mat_c[i]  = -s_mat_c[i] + (1 + ir_mat_c[i]) / (1 + g_nom) * b_lag_v
                snowball_mat[i] = (ir_mat_c[i] - g_nom) / (1 + g_nom) * b_lag_v

                # --- Update lags ---
                y_lag_v    = y_mat[i].copy()
                ypot_lag_v = ypot_mat[i].copy()
                ygap_lag_v = ygap_mat[i].copy()
                pi_lag_v   = pi_mat[i].copy()
                ir_lag_v   = ir_mat_c[i].copy()
                b_lag_v    = b_mat_c[i].copy()

            if c == "Germany":
                b_mat_Germany = b_mat_c.copy()

            if c == "Italy":
                italy_out["dy"]           = dy_mat
                italy_out["g"]            = dy_mat + pi_mat
                italy_out["pi"]           = pi_mat
                italy_out["ir"]           = ir_mat_c
                italy_out["ygap"]         = ygap_mat
                italy_out["s"]            = s_mat_c
                italy_out["s_social"]     = s_social_mat
                italy_out["s_non_social"] = s_ns_mat
                italy_out["b"]            = b_mat_c
                italy_out["snowball"]     = snowball_mat

        # --- Summarise (90% CI, z = 1.645) ---
        z = 1.645
        summary: Dict[str, pd.DataFrame] = {}
        for var, mat in italy_out.items():
            mean_v = mat.mean(axis=1)
            std_v  = mat.std(axis=1)
            summary[var] = pd.DataFrame({
                "year":  proj_years,
                "mean":  mean_v,
                "lower": mean_v - z * std_v,
                "upper": mean_v + z * std_v,
            })

        all_results[scenario] = summary

    return all_results


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def plot_macro_italy(
    results_by_scenario: Dict[str, Dict[str, pd.DataFrame]],
    df_proj: pd.DataFrame,
    variable: str,
    start_year: int = 1970,
    end_year: int = 2050,
) -> plt.Figure:
    """
    Plot historical + projected values of `variable` for Italy.
    Each demographic scenario gets its own coloured line + 90% CI ribbon.
    """
    fig, ax = plt.subplots(figsize=LARGE_FIGSIZE)

    scenarios = list(results_by_scenario.keys())
    colors = (SCENARIO_COLORS * 2)[: len(scenarios)]

    # Historical column name in df_proj
    hist_col_map = {
        "dy":           "dy_Italy",
        "g":            "g_Italy",
        "pi":           "pi_Italy",
        "ir":           "IR_Italy",
        "ygap":         "ygap_Italy",
        "b":            "b_Italy",
        "s":            "s_Italy",
        "s_social":     "s_social_Italy",
        "s_non_social": "s_non_social_Italy",
        "snowball":     "snowball_effect_Italy",
    }
    hist_col = hist_col_map.get(variable)

    if hist_col and hist_col in df_proj.columns:
        hist = df_proj[(df_proj["Year"] >= start_year) & (df_proj["Year"] <= 2024)]
        ax.plot(hist["Year"].values, hist[hist_col].values,
                color="black", linewidth=1.8, linestyle="-", zorder=5,
                label="Historical (Italy)")

    _ylim_map = {
        "dy":           (-0.10,  0.10),
        "g":            (-0.10,  0.10),
        "pi":           ( 0.00,  0.10),
        "ir":           ( 0.00,  0.20),
        "b":            ( 0.00, 10.00),
        "s":            (-0.40,  0.10),
        "s_social":     (-0.30,  0.00),
        "s_non_social": (-0.20,  0.20),
        "ygap":         (-0.10,  0.10),
    }
    ymin, ymax = _ylim_map.get(variable, (-1e6, 1e6))

    # 2024 anchor: the last historical point, used to connect history → projection
    anchor_val = np.nan
    if hist_col and hist_col in df_proj.columns:
        _anchor_row = df_proj[df_proj["Year"] == 2024]
        if len(_anchor_row) > 0:
            anchor_val = float(_anchor_row[hist_col].iloc[0])

    proj_slices = {}
    for scenario in scenarios:
        proj = results_by_scenario[scenario][variable]
        proj = proj[(proj["year"] >= 2025) & (proj["year"] <= end_year)]
        # Prepend 2024 anchor row so the projection line starts at the historical value
        if np.isfinite(anchor_val):
            anchor_row = pd.DataFrame({
                "year": [2024], "mean": [anchor_val],
                "lower": [anchor_val], "upper": [anchor_val],
            })
            proj = pd.concat([anchor_row, proj], ignore_index=True)
        proj_slices[scenario] = proj

    for scenario, color in zip(scenarios, colors):
        proj = proj_slices[scenario]
        label = scenario.replace("_", " ").title()
        ax.plot(proj["year"].values,
                np.clip(proj["mean"].values, ymin, ymax),
                color=color, linewidth=1.6, label=label)
        lo = np.clip(proj["lower"].values, ymin, ymax)
        hi = np.clip(proj["upper"].values, ymin, ymax)
        ax.fill_between(proj["year"].values, lo, hi, color=color, alpha=0.13)

    ax.axvline(x=2024, color="black", linestyle="--", linewidth=0.9, zorder=4)

    ax.set_ylim(ymin, ymax)

    ylims = ax.get_ylim()
    y_top = ylims[1]
    mid_hist = max(start_year, 2010) + (2024 - max(start_year, 2010)) / 2
    mid_proj = 2024 + (end_year - 2024) / 2
    ax.text(mid_hist, y_top, "Historical", ha="center", va="top", fontsize=9, color="gray")
    ax.text(mid_proj, y_top, "Projected",  ha="center", va="top", fontsize=9, color="gray")

    ylabel = VAR_LABELS.get(variable, variable)
    ax.set_xlabel("Year", fontsize=11)
    ax.set_ylabel(ylabel, fontsize=11)
    ax.set_title(f"Italy — {ylabel}", fontsize=12)
    ax.legend(fontsize=9, loc="best")
    ax.grid(True, alpha=0.3)
    ax.set_xlim(start_year, end_year)
    ax.tick_params(axis="x", rotation=45)
    fig.tight_layout()
    return fig
