# =============================================================================
# MIGRATION MODULE - OUR BASELINE WITH AGE-SEX ALLOCATION
# =============================================================================
# Reading guide
# -------------
# This script builds our own baseline for immigration, emigration, and net
# migration. ISTAT, Eurostat, and UN are not used to build the forecast here;
# they are only used later as benchmarks in the plotting script.
#
# The input flows are observed by broad age group. The script therefore:
#   - removes total rows if they exist;
#   - reconstructs annual totals as the sum of age-band counts;
#   - forecasts total immigration and emigration with our own time-series logic;
#   - builds age-sex schedules by combining recent age-band shares, a smooth
#     Rogers-Castro-style single-age template, and the latest Italian/foreign
#     population age-sex structure;
#   - checks that the reconstructed single-age counts sum back exactly to the
#     original broad age-band totals.
# =============================================================================

#!/usr/bin/env python3
"""
02_fit_forecast_migration_own_method_age_sex.py

Own-method migration forecast with age-sex reconstruction.

This script keeps ISTAT, Eurostat and UN out of the baseline. They are used only
by the plotting script as external benchmarks.

Method implemented
------------------
1. Total flows:
   - immigration is forecast from a damped recent log trend;
   - emigration is forecast from a damped recent log trend;
   - net migration is immigration minus emigration;
   - uncertainty is generated by simulations.

2. Age-sex detail:
   - observed broad age-range counts are read by flow, origin, sex and year;
   - recent broad age/origin/sex shares are estimated separately for immigration
     and emigration;
   - forecast total flows are allocated using those recent shares;
   - each broad age range is expanded to single ages 0-100 with a smooth
     Rogers-Castro-style template multiplied by the relevant population structure:
       Origine=Italia       -> italiani.csv
       Origine=Paesi esteri -> stranieri.csv
   - by default, a smooth-and-rake step is used after the first expansion. This is
     important because a purely independent rescaling inside each broad band can
     create artificial cliffs at 17/18, 39/40 and 64/65. The smooth-and-rake step
     smooths the single-age curve across band boundaries and then rakes it back
     to the original broad age-band totals, so each broad age-range total is still
     exactly preserved after expansion.

Default output:
    output/migration/own_method_age_sex
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable, Optional

import numpy as np
import pandas as pd


PROJECT_DIR = Path("/Users/andreaballerini/Downloads/projection_project")

# Immigration is especially sensitive to short-run administrative and post-COVID
# rebound effects. Using 2022-2025 inside the trend fit made the baseline read
# the recent rebound as permanent growth. The default trend window below follows
# the same damped log-trend method, but estimates the structural immigration
# trend from the pre-COVID 2007-2019 period, which is much closer to the ISTAT
# benchmark trajectory while still keeping ISTAT out of the baseline calculation.
DEFAULT_IMMIGRATION_TREND_YEARS = list(range(2007, 2020))
DEFAULT_RECENT_LEVEL_YEARS = [2022, 2023, 2024, 2025]
DEFAULT_EMIGRATION_TREND_YEARS = [
    2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
    2021, 2022, 2023, 2024, 2025,
]
DEFAULT_IMMIGRATION_TREND_DAMPING = 0.90
DEFAULT_EMIGRATION_TREND_DAMPING = 0.93
DEFAULT_IMMIGRATION_SLOPE_CAP = 0.035
DEFAULT_EMIGRATION_SLOPE_CAP = 0.025
FLOW_ORDER = ["immigration", "emigration", "net_migration"]
COMPONENT_ORIGINS = ["Italia", "Paesi esteri"]
COMPONENT_SEXES = ["Maschi", "Femmine"]
AGES = np.arange(0, 101, dtype=int)

# The original literal method is:
#     broad age band total * Rogers-Castro-population share inside that band.
# That is mathematically correct if the only goal is exact preservation of broad
# age-band totals, but it can create artificial spikes at age-band boundaries. The
# default below keeps exact broad-band preservation but smooths across boundaries.
DEFAULT_SINGLE_AGE_METHOD = "smooth_rake"
DEFAULT_SMOOTHING_ITERATIONS = 200
DEFAULT_SMOOTHING_STRENGTH = 0.30

# For ages 0-17, the broad migration band does not let us identify a genuine
# child migration schedule. Applying the adult Rogers-Castro curve inside this
# band makes ages 16-17 too large because the young-adult peak leaks backward
# into the child band.
#
# The default is a compromise:
# - start 0-17 from the relevant recent child population structure;
# - still smooth across 17/18 so the adult migration peak is anticipated without
#   producing a cliff at exactly age 18;
# - rake each broad age band back to its original total after every smoothing
#   pass, so the input grouped counts remain exactly preserved.
DEFAULT_CHILD_AGE_METHOD = "population_bridge"
DEFAULT_CHILD_BRIDGE_ANCHOR = 0.20

ORIGIN_TO_POPULATION = {
    "Italia": "italiani",
    "Paesi esteri": "stranieri",
}


def display_path(path: Path) -> str:
    """
    Format paths in a readable way for console messages.
    """
    try:
        return str(path.resolve().relative_to(PROJECT_DIR.resolve()))
    except Exception:
        return str(path)


def resolve_input_path(path: str | Path) -> Path:
    """
    Resolve an input path using the project folder defaults. This avoids repeated long
    absolute paths in the rest of the script.
    """
    path = Path(path)
    return path if path.is_absolute() else PROJECT_DIR / path


def resolve_output_path(path: str | Path) -> Path:
    """
    Resolve and create the output directory where model results and diagnostics will be
    saved.
    """
    path = Path(path)
    return path if path.is_absolute() else PROJECT_DIR / path


def clean_colname(x: object) -> str:
    """
    Normalize raw column names from ISTAT-style files.
    """
    x = str(x).strip().lower()
    for a, b in [("à", "a"), ("è", "e"), ("é", "e"), ("ì", "i"), ("ò", "o"), ("ù", "u")]:
        x = x.replace(a, b)
    x = re.sub(r"[^a-z0-9]+", "_", x)
    return re.sub(r"_+", "_", x).strip("_")


def norm_label(x: object) -> str:
    """
    Normalize text labels so age bands such as “65 anni e più” can be matched robustly.
    """
    x = str(x).strip().lower()
    for a, b in [("à", "a"), ("è", "e"), ("é", "e"), ("ì", "i"), ("ò", "o"), ("ù", "u")]:
        x = x.replace(a, b)
    return re.sub(r"\s+", " ", x)


def is_total_label(x: object) -> bool:
    """
    Identify total rows in the input. These rows are excluded because annual totals are
    reconstructed from the age-band rows.
    """
    return norm_label(x) in {"totale", "total", "all", "tutti", "tutte"}


def parse_year_list(value: str | None, default: list[int]) -> list[int]:
    """
    Parse recent years from command-line options. These years define the recent age-band
    shares used in the baseline age profile.
    """
    if value is None or str(value).strip() == "":
        return default.copy()
    years = [int(x) for x in re.findall(r"\d{4}", str(value))]
    if not years:
        raise ValueError("Year list must contain four-digit years.")
    return years


def standardize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Bring input files to a consistent internal column structure before reshaping and
    aggregation.
    """
    df = df.loc[:, ~df.columns.astype(str).str.match(r"^Unnamed")].copy()
    df.columns = [clean_colname(c) for c in df.columns]
    aliases = {
        "origin": ["origine", "origin", "citizenship", "cittadinanza", "nationality", "nazionalita"],
        "sex": ["sex", "sesso", "gender"],
        "age_band": ["age", "eta", "classe_eta", "classi_eta", "age_band"],
        "year": ["year", "anno"],
        "count": ["count", "value", "valore", "immigrants", "immigrati", "emigrants", "emigrati"],
        "population": ["population", "popolazione", "pop", "value", "valore"],
        "citizenship": ["citizenship", "cittadinanza"],
    }
    rename = {}
    for target, options in aliases.items():
        for option in options:
            if option in df.columns:
                rename[option] = target
                break
    return df.rename(columns=rename)


def parse_age_band(label: object, max_age: int = 100) -> tuple[int, int]:
    """
    Convert an age-band label into its lower and upper single-age limits.
    """
    s = norm_label(label)
    if is_total_label(s):
        raise ValueError("Total age row is not an age band.")
    if "fino" in s:
        nums = [int(x) for x in re.findall(r"\d+", s)]
        if not nums:
            raise ValueError(f"Could not parse age band: {label}")
        return 0, nums[-1]
    if "piu" in s or "+" in s:
        nums = [int(x) for x in re.findall(r"\d+", s)]
        if not nums:
            raise ValueError(f"Could not parse age band: {label}")
        return nums[0], max_age
    nums = [int(x) for x in re.findall(r"\d+", s)]
    if len(nums) >= 2:
        return nums[0], nums[1]
    if len(nums) == 1:
        return nums[0], nums[0]
    raise ValueError(f"Could not parse age band: {label}")


def read_flow_age_bands(path: str | Path, flow: str) -> pd.DataFrame:
    """Read one migration input file and keep only real component age bands.

    The input files contain:
        origin: Italia / Paesi esteri / Totale
        sex:    Maschi / Femmine / Totale
        age:    four broad age bands, plus sometimes Totale

    For the age-sex reconstruction we intentionally do NOT use the Totale rows.
    Instead, we use the detailed component rows:
        Italia x Maschi/Femmine x broad age band
        Paesi esteri x Maschi/Femmine x broad age band

    This matters because emigrati_input.csv currently has no age=Totale row,
    while immigrati_input.csv does. Summing component broad bands treats both
    flows in the same way and avoids a hidden asymmetry in input reading.
    """
    path = resolve_input_path(path)
    if not path.exists():
        raise FileNotFoundError(f"Missing input file: {path}")
    df = standardize_columns(pd.read_csv(path))
    needed = {"origin", "sex", "age_band", "year", "count"}
    missing = needed - set(df.columns)
    if missing:
        raise ValueError(f"{path.name} missing columns {sorted(missing)}. Found: {list(df.columns)}")

    out = df[["origin", "sex", "age_band", "year", "count"]].copy()
    out["year"] = pd.to_numeric(out["year"], errors="coerce")
    out["count"] = pd.to_numeric(out["count"], errors="coerce")
    out = out.dropna(subset=["year", "count"]).copy()
    out["year"] = out["year"].astype(int)
    out["origin"] = out["origin"].astype(str).str.strip()
    out["sex"] = out["sex"].astype(str).str.strip()
    out["age_band"] = out["age_band"].astype(str).str.strip()

    out = out[
        out["origin"].isin(COMPONENT_ORIGINS)
        & out["sex"].isin(COMPONENT_SEXES)
        & ~out["age_band"].map(is_total_label)
    ].copy()
    if out.empty:
        raise ValueError(f"No component age-band rows found in {path.name}.")

    parsed = out["age_band"].map(parse_age_band)
    out["age_min"] = parsed.map(lambda x: x[0])
    out["age_max"] = parsed.map(lambda x: x[1])
    out["flow"] = flow
    out["source_file"] = display_path(path)
    out["population_citizenship"] = out["origin"].map(ORIGIN_TO_POPULATION)
    return (
        out.groupby(
            ["flow", "year", "origin", "population_citizenship", "sex", "age_band", "age_min", "age_max", "source_file"],
            as_index=False,
        )["count"]
        .sum()
        .sort_values(["flow", "year", "origin", "sex", "age_min"])
    )


def aggregate_observed_totals(age_bands: pd.DataFrame) -> pd.DataFrame:
    """Rebuild total immigration, emigration and net migration from components.

    This is the first diagnostic point: if the component rows are read correctly,
    immigration totals should match the age=Totale row in immigrati_input.csv.
    Emigration has no age=Totale row, so the component sum is the safest total.
    """
    totals = age_bands.groupby(["year", "flow"], as_index=False)["count"].sum()
    wide = totals.pivot(index="year", columns="flow", values="count").reset_index()
    for col in ["immigration", "emigration"]:
        if col not in wide:
            wide[col] = np.nan
    wide["net_migration"] = wide["immigration"] - wide["emigration"]
    return wide[["year", "immigration", "emigration", "net_migration"]].sort_values("year")


def fit_log_linear(year: np.ndarray, value: np.ndarray) -> dict:
    """
    Fit a simple log-linear trend to observed total flows. This gives an independent
    baseline trend for migration totals.
    """
    y = np.log(np.clip(value.astype(float), 1.0, None))
    x = year.astype(float) - float(year.min())
    xmat = np.column_stack([np.ones_like(x), x])
    beta = np.linalg.lstsq(xmat, y, rcond=None)[0]
    fitted = xmat @ beta
    resid = y - fitted
    dof = max(len(y) - 2, 1)
    sigma = float(np.sqrt(np.sum(resid**2) / dof))
    xtx_inv = np.linalg.pinv(xmat.T @ xmat)
    slope_se = float(np.sqrt(max(sigma**2 * xtx_inv[1, 1], 0.0)))
    if len(resid) > 1 and np.std(resid[:-1]) > 0 and np.std(resid[1:]) > 0:
        rho = float(np.corrcoef(resid[:-1], resid[1:])[0, 1])
        rho = float(np.clip(rho, -0.2, 0.85))
    else:
        rho = 0.4
    return {
        "intercept": float(beta[0]),
        "slope": float(beta[1]),
        "slope_se": slope_se,
        "sigma": sigma,
        "rho": rho,
        "residuals": resid,
        "fitted_log": fitted,
    }


def damped_log_trend_path(start_value: float, annual_log_slope: float, years: np.ndarray, damping: float) -> np.ndarray:
    """
    Project a log-linear trend forward with damping so long-run migration levels do not
    explode unrealistically.
    """
    h = np.arange(len(years), dtype=float)
    cumulative = np.cumsum(damping**h)
    return np.log(max(start_value, 1.0)) + annual_log_slope * cumulative


def safe_sigma(values: Iterable[float], floor: float = 0.04, cap: float = 0.35) -> float:
    """
    Estimate a reasonable shock size for simulations while preventing near-zero or extreme
    uncertainty.
    """
    arr = np.asarray(list(values), dtype=float)
    arr = arr[np.isfinite(arr)]
    if len(arr) < 2:
        return floor
    return float(np.clip(np.nanstd(arr, ddof=1), floor, cap))


def simulate_ar1_deviations(n_sim: int, n_years: int, sigma: float, rho: float, rng: np.random.Generator) -> np.ndarray:
    """
    Simulate persistent deviations around the central migration path. Migration shocks are
    autocorrelated rather than independent year by year.
    """
    rho = float(np.clip(rho, -0.2, 0.95))
    eps = np.zeros((n_sim, n_years), dtype=float)
    innov_scale = sigma * np.sqrt(max(1.0 - rho**2, 0.05))
    eps[:, 0] = rng.normal(0.0, sigma, n_sim)
    for j in range(1, n_years):
        eps[:, j] = rho * eps[:, j - 1] + rng.normal(0.0, innov_scale, n_sim)
    return eps


def build_total_forecast(
    observed: pd.DataFrame,
    start_year: int,
    end_year: int,
    immigration_trend_years: list[int],
    emigration_trend_years: list[int],
    recent_level_years: list[int],
    n_sim: int,
    random_seed: int,
    immigration_trend_damping: float,
    emigration_trend_damping: float,
    immigration_slope_cap: float,
    emigration_slope_cap: float,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Build the total migration baseline and its uncertainty intervals.

    Important: ISTAT, Eurostat and UN are not used here. They enter only in the
    plotting script as benchmarks.

    The baseline follows the report logic:
    - immigration is forecast using a damped log trend estimated from recent
      non-COVID-shock years;
    - emigration is forecast using the same damped log trend logic;
    - net migration is not forecast separately. It is derived mechanically as
      immigration minus emigration.

    The simulations mirror the mortality/fertility style: uncertainty is not a
    decorative confidence band from benchmarks; it is generated from stochastic
    paths around the model assumptions.
    """
    years = np.arange(start_year, end_year + 1)
    rng = np.random.default_rng(random_seed)

    recent_levels = observed[observed["year"].isin(recent_level_years)].copy()
    if recent_levels.empty:
        raise ValueError(f"No recent level years available: {recent_level_years}")
    missing_recent = sorted(set(recent_level_years) - set(recent_levels["year"].unique()))

    imm_trend = observed[observed["year"].isin(immigration_trend_years)].copy()
    if len(imm_trend) < 5:
        raise ValueError(f"At least five immigration trend years are needed. Found {len(imm_trend)}.")
    missing_imm = sorted(set(immigration_trend_years) - set(imm_trend["year"].unique()))
    imm_fit = fit_log_linear(imm_trend["year"].to_numpy(), imm_trend["immigration"].to_numpy())
    immigration_slope_cap = abs(float(immigration_slope_cap))
    emigration_slope_cap = abs(float(emigration_slope_cap))
    imm_slope = float(np.clip(imm_fit["slope"], -immigration_slope_cap, immigration_slope_cap))
    imm_slope_se = min(max(imm_fit["slope_se"], 0.001), 0.012)
    sigma_imm = float(np.clip(imm_fit["sigma"], 0.035, 0.25))
    rho_imm = float(np.clip(imm_fit["rho"], 0.2, 0.85))
    immigration_start = float(recent_levels["immigration"].mean())

    emi_trend = observed[observed["year"].isin(emigration_trend_years)].copy()
    if len(emi_trend) < 5:
        raise ValueError(f"At least five emigration trend years are needed. Found {len(emi_trend)}.")
    missing_emi = sorted(set(emigration_trend_years) - set(emi_trend["year"].unique()))
    emi_fit = fit_log_linear(emi_trend["year"].to_numpy(), emi_trend["emigration"].to_numpy())
    emi_slope = float(np.clip(emi_fit["slope"], -emigration_slope_cap, emigration_slope_cap))
    emi_slope_se = min(max(emi_fit["slope_se"], 0.001), 0.012)
    sigma_emi = float(np.clip(emi_fit["sigma"], 0.035, 0.25))
    rho_emi = float(np.clip(emi_fit["rho"], 0.2, 0.85))
    emigration_start = float(recent_levels["emigration"].mean())

    immigration_log_central = damped_log_trend_path(immigration_start, imm_slope, years, immigration_trend_damping)
    immigration_mean = np.exp(immigration_log_central)
    emigration_log_central = damped_log_trend_path(emigration_start, emi_slope, years, emigration_trend_damping)
    emigration_mean = np.exp(emigration_log_central)
    net_mean = immigration_mean - emigration_mean

    mean = pd.DataFrame(
        {
            "year": years,
            "immigration": immigration_mean,
            "emigration": emigration_mean,
            "net_migration": net_mean,
            "scenario": "baseline_damped_trend_immigration_and_emigration",
            "method": "own_method_damped_log_trend_total_flows",
            "citizenship_scope": "total_all_citizenships",
        }
    )

    imm_damped_cumulative = np.cumsum(immigration_trend_damping ** np.arange(len(years), dtype=float))
    emi_damped_cumulative = np.cumsum(emigration_trend_damping ** np.arange(len(years), dtype=float))

    imm_slope_draw = rng.normal(imm_slope, imm_slope_se, n_sim)
    imm_slope_draw = np.clip(imm_slope_draw, -(immigration_slope_cap + 0.005), immigration_slope_cap + 0.005)
    imm_start_draw = rng.normal(np.log(max(immigration_start, 1.0)), sigma_imm, n_sim)
    imm_eps = simulate_ar1_deviations(n_sim, len(years), sigma_imm, rho_imm, rng)
    imm_log = imm_start_draw[:, None] + imm_slope_draw[:, None] * imm_damped_cumulative[None, :] + imm_eps
    imm_sim = np.exp(imm_log)

    emi_slope_draw = rng.normal(emi_slope, emi_slope_se, n_sim)
    emi_slope_draw = np.clip(emi_slope_draw, -(emigration_slope_cap + 0.010), emigration_slope_cap + 0.010)
    emi_start_draw = rng.normal(np.log(max(emigration_start, 1.0)), sigma_emi, n_sim)
    emi_eps = simulate_ar1_deviations(n_sim, len(years), sigma_emi, rho_emi, rng)
    emi_log = emi_start_draw[:, None] + emi_slope_draw[:, None] * emi_damped_cumulative[None, :] + emi_eps
    emi_sim = np.exp(emi_log)
    net_sim = imm_sim - emi_sim

    sim = pd.DataFrame(
        {
            "sim": np.repeat(np.arange(1, n_sim + 1), len(years)),
            "year": np.tile(years, n_sim),
            "immigration": imm_sim.reshape(-1),
            "emigration": emi_sim.reshape(-1),
            "net_migration": net_sim.reshape(-1),
        }
    )

    intervals = summarize_total_simulations(years, {
        "immigration": (imm_sim, immigration_mean),
        "emigration": (emi_sim, emigration_mean),
        "net_migration": (net_sim, net_mean),
    })

    params = pd.DataFrame(
        [
            {
                "method": "own_method_damped_log_trend_total_flows",
                "report_interpretation": (
                    "baseline immigration and emigration are forecast from recent damped log trends; "
                    "net migration is derived as immigration minus emigration"
                ),
                "start_year": start_year,
                "end_year": end_year,
                "n_sim": n_sim,
                "random_seed": random_seed,
                "recent_level_years_requested": ",".join(map(str, recent_level_years)),
                "recent_level_years_missing": ",".join(map(str, missing_recent)),
                "immigration_trend_years_requested": ",".join(map(str, immigration_trend_years)),
                "immigration_trend_years_missing": ",".join(map(str, missing_imm)),
                "immigration_start_level": immigration_start,
                "immigration_log_slope_raw": imm_fit["slope"],
                "immigration_log_slope_used": imm_slope,
                "immigration_slope_se": imm_slope_se,
                "immigration_log_resid_sd": sigma_imm,
                "immigration_resid_rho": rho_imm,
                "immigration_trend_damping": immigration_trend_damping,
                "immigration_slope_cap": immigration_slope_cap,
                "emigration_trend_years_requested": ",".join(map(str, emigration_trend_years)),
                "emigration_trend_years_missing": ",".join(map(str, missing_emi)),
                "emigration_start_level": emigration_start,
                "emigration_log_slope_raw": emi_fit["slope"],
                "emigration_log_slope_used": emi_slope,
                "emigration_slope_se": emi_slope_se,
                "emigration_log_resid_sd": sigma_emi,
                "emigration_resid_rho": rho_emi,
                "emigration_trend_damping": emigration_trend_damping,
                "emigration_slope_cap": emigration_slope_cap,
            }
        ]
    )
    return mean, intervals, sim, params


def summarize_total_simulations(years: np.ndarray, arrays: dict[str, tuple[np.ndarray, np.ndarray]]) -> pd.DataFrame:
    """
    Convert simulated total-flow paths into medians and prediction intervals.
    """
    rows = []
    quantiles = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    qnames = ["p05", "p10", "p25", "p50", "p75", "p90", "p95"]
    for flow, (arr, central) in arrays.items():
        qs = np.quantile(arr, quantiles, axis=0)
        for j, year in enumerate(years):
            row = {
                "year": int(year),
                "flow": flow,
                "mean": float(central[j]),
                "citizenship_scope": "total_all_citizenships",
                "interval_method": "simulation_prediction_interval",
            }
            for qname, qvals in zip(qnames, qs):
                row[qname] = float(qvals[j])
            rows.append(row)
    return pd.DataFrame(rows)


def rogers_castro_template(flow: str) -> pd.DataFrame:
    """Create a smooth Rogers-Castro-style prior profile over ages 0-100.

    This is not data fitting. It is a smooth demographic prior with:
    - a child/family component,
    - a young adult labour/student migration component,
    - an older adult component,
    - a small retirement/old-age component.

    The template is later multiplied by the relevant population age structure and
    calibrated to observed broad age-band totals.
    """
    age = AGES.astype(float)
    if flow == "immigration":
        profile = (
            0.035
            + 0.30 * np.exp(-0.5 * ((age - 5.0) / 8.0) ** 2)
            + 1.00 * np.exp(-0.5 * ((age - 29.0) / 8.5) ** 2)
            + 0.32 * np.exp(-0.5 * ((age - 40.0) / 11.0) ** 2)
            + 0.10 * np.exp(-0.5 * ((age - 66.0) / 8.0) ** 2)
            + 0.05 * np.exp(-0.5 * ((age - 83.0) / 10.0) ** 2)
        )
    elif flow == "emigration":
        profile = (
            0.030
            + 0.24 * np.exp(-0.5 * ((age - 6.0) / 8.0) ** 2)
            + 1.00 * np.exp(-0.5 * ((age - 31.0) / 9.5) ** 2)
            + 0.25 * np.exp(-0.5 * ((age - 43.0) / 12.0) ** 2)
            + 0.12 * np.exp(-0.5 * ((age - 66.0) / 8.0) ** 2)
            + 0.05 * np.exp(-0.5 * ((age - 84.0) / 10.0) ** 2)
        )
    else:
        profile = 0.5 * (
            rogers_castro_template("immigration")["template_weight"].to_numpy()
            + rogers_castro_template("emigration")["template_weight"].to_numpy()
        )
    profile = np.clip(profile, 1e-12, None)
    profile = profile / profile.sum()
    return pd.DataFrame({"flow": flow, "age": AGES, "template_weight": profile})


def load_population(path: str | Path, expected_citizenship: str) -> pd.DataFrame:
    """
    Load the most recent age-sex population structure used to split flows by sex and refine
    single-age allocation.
    """
    path = resolve_input_path(path)
    if not path.exists():
        raise FileNotFoundError(f"Missing population file: {path}")
    df = standardize_columns(pd.read_csv(path))
    if "age" not in df.columns and "age_band" in df.columns:
        df = df.rename(columns={"age_band": "age"})
    needed = {"sex", "age", "year", "population"}
    missing = needed - set(df.columns)
    if missing:
        raise ValueError(f"{path.name} missing columns {sorted(missing)}. Found: {list(df.columns)}")
    out = df[["sex", "age", "year", "population"]].copy()
    out["sex"] = out["sex"].astype(str).str.strip()
    out["age"] = pd.to_numeric(out["age"], errors="coerce")
    out["year"] = pd.to_numeric(out["year"], errors="coerce")
    out["population"] = pd.to_numeric(out["population"], errors="coerce")
    out = out.dropna(subset=["sex", "age", "year", "population"]).copy()
    out["age"] = out["age"].astype(int)
    out["year"] = out["year"].astype(int)
    out = out[out["age"].between(0, 100) & out["sex"].isin(COMPONENT_SEXES)].copy()
    out["population_citizenship"] = expected_citizenship
    out["population_file"] = display_path(path)
    return out.groupby(["population_citizenship", "sex", "age", "year", "population_file"], as_index=False)["population"].sum()


def nearest_population_year(pop: pd.DataFrame, requested_year: int) -> int:
    """
    Choose the population year closest to the target year, usually the most recent available
    structure.
    """
    years = np.asarray(sorted(pop["year"].unique()), dtype=int)
    prior = years[years <= requested_year]
    if len(prior):
        return int(prior.max())
    return int(years.min())


def single_age_weights(
    flow: str,
    origin: str,
    sex: str,
    year: int,
    age_min: int,
    age_max: int,
    populations: pd.DataFrame,
    templates: dict[str, pd.DataFrame],
    child_age_method: str = DEFAULT_CHILD_AGE_METHOD,
) -> tuple[pd.DataFrame, int]:
    """Return the unadjusted Rogers-Castro x population shares inside one age band.

    This helper is deliberately narrow: it looks only at one broad age band. The
    result is useful both for the literal old method and as the starting point for
    the smoother expansion below.

    The population file used depends on the migration input origin:
    - Origine=Italia uses the Italian population age-sex structure.
    - Origine=Paesi esteri uses the foreign population age-sex structure.

    For ages 0-17, the default is different from adult ages: it uses population
    structure as the starting point. That is intentional. A Rogers-Castro
    adult/young-adult peak should not be allowed to dominate the child age band
    when the only observed migration information is a single wide 0-17 total.

    For forecast years beyond the last available population year, the nearest
    previous population structure is used. With the current files, this means
    forecast years after 2026 use the 2026 population age-sex structure.
    """
    pop_cit = ORIGIN_TO_POPULATION[origin]
    pop_subset_all_years = populations[
        (populations["population_citizenship"] == pop_cit) & (populations["sex"] == sex)
    ].copy()
    if pop_subset_all_years.empty:
        raise ValueError(f"No population structure for {pop_cit}, {sex}.")
    pop_year = nearest_population_year(pop_subset_all_years, year)
    pop = pop_subset_all_years[pop_subset_all_years["year"].eq(pop_year)][["age", "population"]].copy()
    template = templates[flow][["age", "template_weight"]].copy()
    weights = template.merge(pop, on="age", how="left")
    weights["population"] = weights["population"].fillna(0.0).clip(lower=0.0)
    weights = weights[weights["age"].between(age_min, age_max)].copy()
    if age_max <= 17 and child_age_method in {"population_only", "population_bridge"}:
        weights["raw_weight"] = weights["population"]
    elif child_age_method in {"population_only", "population_bridge", "template_population"}:
        weights["raw_weight"] = weights["template_weight"] * weights["population"]
    else:
        raise ValueError(f"Unknown child_age_method: {child_age_method}")
    if weights["raw_weight"].sum() <= 0:
        weights["raw_weight"] = weights["template_weight"]
    weights["single_age_share_inside_band"] = weights["raw_weight"] / weights["raw_weight"].sum()
    return weights[["age", "single_age_share_inside_band"]], pop_year


def smooth_counts_once(counts: np.ndarray) -> np.ndarray:
    """Apply one gentle five-point smoothing pass to a single-age curve.

    The edge padding avoids creating artificial losses at age 0 and age 100.
    This smoothing pass does not preserve broad age-band totals by itself; the
    next helper, rescale_to_band_totals, restores those totals exactly.
    """
    kernel = np.array([1.0, 4.0, 6.0, 4.0, 1.0], dtype=float) / 16.0
    return np.convolve(np.pad(counts, (2, 2), mode="edge"), kernel, mode="valid")


def smooth_counts_with_optional_child_barrier(counts: np.ndarray, child_age_method: str) -> np.ndarray:
    """Smooth a curve, optionally preventing adult ages from pulling up age 17.

    population_only is the strict option: ages 0-17 are left unchanged during
    smoothing. This preserves the child population profile exactly, but it can
    leave a visible jump at 17/18 if the observed 18-39 migration band is much
    heavier than the observed 0-17 band.

    population_bridge, the default, does not use this hard barrier. Instead, the
    smoothing loop below allows information to pass across 17/18 and then pulls
    child ages back toward the initial population-based child profile.
    """
    counts = np.asarray(counts, dtype=float)
    if child_age_method == "population_only":
        out = counts.copy()
        out[18:] = smooth_counts_once(counts[18:])
        return out
    return smooth_counts_once(counts)


def rescale_to_band_totals(counts: np.ndarray, band_rows: pd.DataFrame, count_col: str) -> np.ndarray:
    """Rake a single-age curve back to the known broad age-band totals.

    For every broad band, all ages inside the band are multiplied by one scalar
    so the sum inside the band equals the observed/forecast broad-band total.
    The final age in the band receives a tiny floating-point adjustment, making
    the equality exact to machine precision.
    """
    out = np.clip(np.asarray(counts, dtype=float).copy(), 0.0, None)
    for _, row in band_rows.iterrows():
        idx = np.arange(int(row["age_min"]), int(row["age_max"]) + 1)
        target = float(row[count_col])
        current = float(out[idx].sum())
        if current > 0:
            out[idx] *= target / current
        else:
            out[idx] = target / len(idx)
        out[idx[-1]] += target - float(out[idx].sum())
    return out


def expand_component_year_to_single_age(
    component_bands: pd.DataFrame,
    populations: pd.DataFrame,
    templates: dict[str, pd.DataFrame],
    count_col: str,
    single_age_method: str,
    smoothing_iterations: int,
    smoothing_strength: float,
    child_age_method: str,
    child_bridge_anchor: float,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Expand one flow-year-origin-sex component from broad bands to ages 0-100.

    The input group contains all broad age bands for exactly one:
        flow x year x origin x sex

    Two expansion methods are supported:

    1. band_rescaled
       This is the literal method used in the first version:
       each age band is expanded independently using Rogers-Castro x population
       shares inside that band. It preserves the broad totals exactly, but can
       create boundary artifacts when adjacent broad bands have very different
       totals per underlying template weight.

    2. smooth_rake
       This starts from the same literal expansion, then repeatedly:
       - smooths the full age 0-100 curve across age-band boundaries;
       - rakes/rescales each broad band back to its exact original total.

       This keeps the constraints we care about while avoiding artificial spikes
       at ages 17, 40 and 65. It is closer to the idea of using Rogers-Castro as
       a smooth single-age prior, then calibrating it to observed grouped data.

    When child_age_method="population_bridge", the initial 0-17 profile is still
    population-based, but each smoothing iteration is softly anchored back to that
    starting child profile. This is the compromise between the actual recent
    child distribution and the theoretical continuity of the migration schedule:
    the adult peak is anticipated before age 18, but age 17 is not allowed to
    become a pure young-adult-template artifact.
    """
    first = component_bands.iloc[0]
    flow = str(first["flow"])
    year = int(first["year"])
    origin = str(first["origin"])
    sex = str(first["sex"])
    pop_cit = str(first["population_citizenship"])

    counts = np.zeros(len(AGES), dtype=float)
    pop_years_used = []

    # First pass: exact independent allocation within each broad age band.
    for _, row in component_bands.iterrows():
        weights, pop_year = single_age_weights(
            flow=flow,
            origin=origin,
            sex=sex,
            year=year,
            age_min=int(row["age_min"]),
            age_max=int(row["age_max"]),
            populations=populations,
            templates=templates,
            child_age_method=child_age_method,
        )
        pop_years_used.append(pop_year)
        idx = weights["age"].to_numpy(dtype=int)
        counts[idx] = float(row[count_col]) * weights["single_age_share_inside_band"].to_numpy(dtype=float)

    counts = rescale_to_band_totals(counts, component_bands, count_col)

    if single_age_method == "smooth_rake":
        smoothing_strength = float(np.clip(smoothing_strength, 0.0, 1.0))
        child_bridge_anchor = float(np.clip(child_bridge_anchor, 0.0, 1.0))
        initial_counts = counts.copy()
        for _ in range(max(int(smoothing_iterations), 0)):
            smoothed = smooth_counts_with_optional_child_barrier(counts, child_age_method)
            counts = (1.0 - smoothing_strength) * counts + smoothing_strength * smoothed
            if child_age_method == "population_bridge":
                counts[:18] = (
                    (1.0 - child_bridge_anchor) * counts[:18]
                    + child_bridge_anchor * initial_counts[:18]
                )
            counts = rescale_to_band_totals(counts, component_bands, count_col)
    elif single_age_method != "band_rescaled":
        raise ValueError(f"Unknown single_age_method: {single_age_method}")

    rows = []
    diag_rows = []
    for _, band in component_bands.iterrows():
        age_min = int(band["age_min"])
        age_max = int(band["age_max"])
        idx = np.arange(age_min, age_max + 1)
        target = float(band[count_col])
        band_counts = counts[idx].copy()
        band_sum = float(band_counts.sum())
        share_inside = band_counts / band_sum if band_sum > 0 else np.full(len(idx), 1.0 / len(idx))
        for age, count, share in zip(idx, band_counts, share_inside):
            rows.append(
                {
                    "flow": flow,
                    "year": year,
                    "origin": origin,
                    "population_citizenship": pop_cit,
                    "sex": sex,
                    "age_band": band["age_band"],
                    "age_min": age_min,
                    "age_max": age_max,
                    "population_year_used": max(pop_years_used) if pop_years_used else np.nan,
                    "age": int(age),
                    "single_age_share_inside_band": float(share),
                    "count": float(count),
                    "single_age_method": single_age_method,
                    "child_age_method": child_age_method,
                    "child_bridge_anchor": child_bridge_anchor,
                }
            )
        diag_rows.append(
            {
                "flow": flow,
                "year": year,
                "origin": origin,
                "population_citizenship": pop_cit,
                "sex": sex,
                "age_band": band["age_band"],
                "age_min": age_min,
                "age_max": age_max,
                "population_year_used": max(pop_years_used) if pop_years_used else np.nan,
                "original_age_band_count": target,
                "reconstructed_single_age_sum": band_sum,
                "difference": band_sum - target,
                "n_single_ages": int(len(idx)),
                "single_age_method": single_age_method,
                "child_age_method": child_age_method,
                "child_bridge_anchor": child_bridge_anchor,
            }
        )
    return pd.DataFrame(rows), pd.DataFrame(diag_rows)


def estimate_recent_component_shares(age_bands: pd.DataFrame, recent_years: list[int]) -> pd.DataFrame:
    """Estimate how total flows split by origin, sex and broad age band.

    Example: what share of all immigration belongs to
        Paesi esteri x Maschi x 18-39 anni?

    These shares are estimated from recent years and then applied to each future
    total flow. This makes total immigration/emigration the modelled object and
    age-sex-origin structure the allocation layer.
    """
    sub = age_bands[age_bands["year"].isin(recent_years)].copy()
    if sub.empty:
        raise ValueError(f"No age-band rows found for recent share years: {recent_years}")
    grouped = (
        sub.groupby(
            ["flow", "origin", "population_citizenship", "sex", "age_band", "age_min", "age_max"],
            as_index=False,
        )["count"]
        .sum()
        .rename(columns={"count": "recent_count_sum"})
    )
    totals = grouped.groupby("flow", as_index=False)["recent_count_sum"].sum().rename(columns={"recent_count_sum": "flow_recent_sum"})
    out = grouped.merge(totals, on="flow", how="left")
    out["share_of_flow"] = out["recent_count_sum"] / out["flow_recent_sum"]
    out["recent_years_used"] = ",".join(map(str, sorted(sub["year"].unique())))
    return out.sort_values(["flow", "origin", "sex", "age_min"])


def make_forecast_age_bands(total_mean: pd.DataFrame, shares: pd.DataFrame) -> pd.DataFrame:
    """
    Apply recent age-band shares to forecasted total flows to produce future age-band
    counts.
    """
    rows = []
    for _, total in total_mean.iterrows():
        year = int(total["year"])
        for flow in ["immigration", "emigration"]:
            flow_shares = shares[shares["flow"].eq(flow)].copy()
            tmp = flow_shares.copy()
            tmp["year"] = year
            tmp["count"] = float(total[flow]) * tmp["share_of_flow"]
            rows.append(tmp)
    out = pd.concat(rows, ignore_index=True)
    return out[
        [
            "flow", "year", "origin", "population_citizenship", "sex", "age_band", "age_min", "age_max",
            "count", "share_of_flow", "recent_count_sum", "flow_recent_sum", "recent_years_used",
        ]
    ]


def expand_age_bands_to_single_age(
    age_bands: pd.DataFrame,
    populations: pd.DataFrame,
    templates: dict[str, pd.DataFrame],
    count_col: str = "count",
    single_age_method: str = DEFAULT_SINGLE_AGE_METHOD,
    smoothing_iterations: int = DEFAULT_SMOOTHING_ITERATIONS,
    smoothing_strength: float = DEFAULT_SMOOTHING_STRENGTH,
    child_age_method: str = DEFAULT_CHILD_AGE_METHOD,
    child_bridge_anchor: float = DEFAULT_CHILD_BRIDGE_ANCHOR,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Expand every flow-year-origin-sex group to single ages.

    Grouping before expansion is crucial for the smooth_rake method: smoothing
    can only remove boundary artifacts if it can see all adjacent age bands at
    the same time.
    """
    row_parts = []
    diag_parts = []
    group_cols = ["flow", "year", "origin", "population_citizenship", "sex"]
    for _, group in age_bands.groupby(group_cols, dropna=False, sort=False):
        rows, diag = expand_component_year_to_single_age(
            group.sort_values("age_min"),
            populations=populations,
            templates=templates,
            count_col=count_col,
            single_age_method=single_age_method,
            smoothing_iterations=smoothing_iterations,
            smoothing_strength=smoothing_strength,
            child_age_method=child_age_method,
            child_bridge_anchor=child_bridge_anchor,
        )
        row_parts.append(rows)
        diag_parts.append(diag)
    return pd.concat(row_parts, ignore_index=True), pd.concat(diag_parts, ignore_index=True)


def make_single_age_flow_shares(
    age_bands_for_shares: pd.DataFrame,
    populations: pd.DataFrame,
    templates: dict[str, pd.DataFrame],
    single_age_method: str = DEFAULT_SINGLE_AGE_METHOD,
    smoothing_iterations: int = DEFAULT_SMOOTHING_ITERATIONS,
    smoothing_strength: float = DEFAULT_SMOOTHING_STRENGTH,
    child_age_method: str = DEFAULT_CHILD_AGE_METHOD,
    child_bridge_anchor: float = DEFAULT_CHILD_BRIDGE_ANCHOR,
) -> pd.DataFrame:
    expanded, _ = expand_age_bands_to_single_age(
        age_bands_for_shares.rename(columns={"share_of_flow": "count"}),
        populations,
        templates,
        count_col="count",
        single_age_method=single_age_method,
        smoothing_iterations=smoothing_iterations,
        smoothing_strength=smoothing_strength,
        child_age_method=child_age_method,
        child_bridge_anchor=child_bridge_anchor,
    )
    expanded = expanded.rename(columns={"count": "share_of_flow_single_age"})
    return expanded[
        [
            "flow", "year", "origin", "population_citizenship", "sex", "age", "age_band", "age_min", "age_max",
            "single_age_share_inside_band", "share_of_flow_single_age", "population_year_used",
        ]
    ].sort_values(["flow", "year", "origin", "sex", "age"])


def append_net_single_age(mean_single: pd.DataFrame) -> pd.DataFrame:
    """
    Compute net migration at single age and sex by subtracting emigration from immigration.
    """
    key = ["year", "origin", "population_citizenship", "sex", "age"]
    imm = mean_single[mean_single["flow"].eq("immigration")][key + ["count"]].rename(columns={"count": "immigration"})
    emi = mean_single[mean_single["flow"].eq("emigration")][key + ["count"]].rename(columns={"count": "emigration"})
    net = imm.merge(emi, on=key, how="outer").fillna({"immigration": 0.0, "emigration": 0.0})
    net["count"] = net["immigration"] - net["emigration"]
    net["flow"] = "net_migration"
    net["age_band"] = "single_age_net"
    net["age_min"] = net["age"]
    net["age_max"] = net["age"]
    net["single_age_share_inside_band"] = np.nan
    net["population_year_used"] = np.nan
    cols = [
        "flow", "year", "origin", "population_citizenship", "sex", "age", "age_band", "age_min", "age_max",
        "single_age_share_inside_band", "count", "population_year_used",
    ]
    return pd.concat([mean_single[cols], net[cols]], ignore_index=True).sort_values(["flow", "year", "origin", "sex", "age"])


def append_net_age_bands(mean_bands: pd.DataFrame) -> pd.DataFrame:
    """
    Compute net migration by broad age band by subtracting emigration from immigration.
    """
    key = ["year", "origin", "population_citizenship", "sex", "age_band", "age_min", "age_max"]
    imm = mean_bands[mean_bands["flow"].eq("immigration")][key + ["count"]].rename(columns={"count": "immigration"})
    emi = mean_bands[mean_bands["flow"].eq("emigration")][key + ["count"]].rename(columns={"count": "emigration"})
    net = imm.merge(emi, on=key, how="outer").fillna({"immigration": 0.0, "emigration": 0.0})
    net["count"] = net["immigration"] - net["emigration"]
    net["flow"] = "net_migration"
    keep_cols = ["flow", *key, "count"]
    return pd.concat([mean_bands[keep_cols], net[keep_cols]], ignore_index=True).sort_values(
        ["flow", "year", "origin", "sex", "age_min"]
    )


def summarize_age_sex_intervals(
    total_sim: pd.DataFrame,
    single_age_shares: pd.DataFrame,
    age_band_shares: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    years = sorted(total_sim["year"].unique())
    quantiles = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    qnames = ["p05", "p10", "p25", "p50", "p75", "p90", "p95"]
    single_rows = []
    band_rows = []

    sim_by_year = {int(y): g.sort_values("sim") for y, g in total_sim.groupby("year")}

    for year in years:
        sims = sim_by_year[int(year)]
        imm_sims = sims["immigration"].to_numpy(dtype=float)
        emi_sims = sims["emigration"].to_numpy(dtype=float)

        year_single = single_age_shares[single_age_shares["year"].eq(year)].copy()
        for flow, sim_values in [("immigration", imm_sims), ("emigration", emi_sims)]:
            g = year_single[year_single["flow"].eq(flow)].copy()
            shares = g["share_of_flow_single_age"].to_numpy(dtype=float)
            q = np.quantile(sim_values[:, None] * shares[None, :], quantiles, axis=0)
            mean = float(sim_values.mean()) * shares
            for idx, (_, row) in enumerate(g.iterrows()):
                out = {
                    "year": int(year),
                    "flow": flow,
                    "origin": row["origin"],
                    "population_citizenship": row["population_citizenship"],
                    "sex": row["sex"],
                    "age": int(row["age"]),
                    "age_band": row["age_band"],
                    "mean": float(mean[idx]),
                    "interval_method": "total_flow_simulation_with_fixed_age_sex_shares",
                }
                for qname, qvalues in zip(qnames, q):
                    out[qname] = float(qvalues[idx])
                single_rows.append(out)

        wide_single = year_single.pivot_table(
            index=["origin", "population_citizenship", "sex", "age"],
            columns="flow",
            values="share_of_flow_single_age",
            aggfunc="sum",
            fill_value=0.0,
        ).reset_index()
        for col in ["immigration", "emigration"]:
            if col not in wide_single:
                wide_single[col] = 0.0
        imm_share = wide_single["immigration"].to_numpy(dtype=float)
        emi_share = wide_single["emigration"].to_numpy(dtype=float)
        net_values = imm_sims[:, None] * imm_share[None, :] - emi_sims[:, None] * emi_share[None, :]
        q = np.quantile(net_values, quantiles, axis=0)
        mean = net_values.mean(axis=0)
        for idx, (_, row) in enumerate(wide_single.iterrows()):
            out = {
                "year": int(year),
                "flow": "net_migration",
                "origin": row["origin"],
                "population_citizenship": row["population_citizenship"],
                "sex": row["sex"],
                "age": int(row["age"]),
                "age_band": "single_age_net",
                "mean": float(mean[idx]),
                "interval_method": "component_total_flow_simulation_with_fixed_age_sex_shares",
            }
            for qname, qvalues in zip(qnames, q):
                out[qname] = float(qvalues[idx])
            single_rows.append(out)

        year_bands = age_band_shares[age_band_shares["year"].eq(year)].copy()
        for flow, sim_values in [("immigration", imm_sims), ("emigration", emi_sims)]:
            g = year_bands[year_bands["flow"].eq(flow)].copy()
            shares = g["share_of_flow"].to_numpy(dtype=float)
            q = np.quantile(sim_values[:, None] * shares[None, :], quantiles, axis=0)
            mean = float(sim_values.mean()) * shares
            for idx, (_, row) in enumerate(g.iterrows()):
                out = {
                    "year": int(year),
                    "flow": flow,
                    "origin": row["origin"],
                    "population_citizenship": row["population_citizenship"],
                    "sex": row["sex"],
                    "age_band": row["age_band"],
                    "age_min": int(row["age_min"]),
                    "age_max": int(row["age_max"]),
                    "mean": float(mean[idx]),
                    "interval_method": "total_flow_simulation_with_fixed_age_band_shares",
                }
                for qname, qvalues in zip(qnames, q):
                    out[qname] = float(qvalues[idx])
                band_rows.append(out)

        wide_band = year_bands.pivot_table(
            index=["origin", "population_citizenship", "sex", "age_band", "age_min", "age_max"],
            columns="flow",
            values="share_of_flow",
            aggfunc="sum",
            fill_value=0.0,
        ).reset_index()
        for col in ["immigration", "emigration"]:
            if col not in wide_band:
                wide_band[col] = 0.0
        imm_share = wide_band["immigration"].to_numpy(dtype=float)
        emi_share = wide_band["emigration"].to_numpy(dtype=float)
        net_values = imm_sims[:, None] * imm_share[None, :] - emi_sims[:, None] * emi_share[None, :]
        q = np.quantile(net_values, quantiles, axis=0)
        mean = net_values.mean(axis=0)
        for idx, (_, row) in enumerate(wide_band.iterrows()):
            out = {
                "year": int(year),
                "flow": "net_migration",
                "origin": row["origin"],
                "population_citizenship": row["population_citizenship"],
                "sex": row["sex"],
                "age_band": row["age_band"],
                "age_min": int(row["age_min"]),
                "age_max": int(row["age_max"]),
                "mean": float(mean[idx]),
                "interval_method": "component_total_flow_simulation_with_fixed_age_band_shares",
            }
            for qname, qvalues in zip(qnames, q):
                out[qname] = float(qvalues[idx])
            band_rows.append(out)

    return pd.DataFrame(single_rows), pd.DataFrame(band_rows)


def save_component_total_files(total_mean: pd.DataFrame, total_intervals: pd.DataFrame, outdir: Path) -> None:
    """
    Save separate total-flow outputs for immigration, emigration, and net migration.
    """
    for flow in FLOW_ORDER:
        total_mean[["year", flow, "method", "scenario", "citizenship_scope"]].rename(columns={flow: "count"}).assign(flow=flow)[
            ["year", "flow", "count", "method", "scenario", "citizenship_scope"]
        ].to_csv(outdir / f"{flow}_own_method_age_sex_mean.csv", index=False)
        total_intervals[total_intervals["flow"].eq(flow)].to_csv(outdir / f"{flow}_own_method_age_sex_intervals.csv", index=False)


def total_check(single_age_mean: pd.DataFrame, total_mean: pd.DataFrame) -> pd.DataFrame:
    """
    Check whether the age-sex schedules sum back to the total migration forecasts.
    """
    totals = single_age_mean.groupby(["year", "flow"], as_index=False)["count"].sum().rename(columns={"count": "single_age_sum"})
    total_long = total_mean.melt(id_vars=["year"], value_vars=FLOW_ORDER, var_name="flow", value_name="total_forecast")
    out = totals.merge(total_long, on=["year", "flow"], how="left")
    out["difference"] = out["single_age_sum"] - out["total_forecast"]
    return out.sort_values(["flow", "year"])


def main() -> None:
    """
    Run the complete script from inputs to outputs.
    """
    parser = argparse.ArgumentParser(description="Fit own-method migration forecast and expand to age-sex single ages.")
    parser.add_argument("--immigration-input", default="immigrati_input.csv")
    parser.add_argument("--emigration-input", default="emigrati_input.csv")
    parser.add_argument("--italian-population", default="italiani.csv")
    parser.add_argument("--foreign-population", default="stranieri.csv")
    parser.add_argument("--output-dir", default="output/migration/own_method_age_sex")
    parser.add_argument("--start-year", type=int, default=2025)
    parser.add_argument("--end-year", type=int, default=2075)
    parser.add_argument("--immigration-trend-years", default=",".join(map(str, DEFAULT_IMMIGRATION_TREND_YEARS)))
    parser.add_argument("--emigration-trend-years", default=",".join(map(str, DEFAULT_EMIGRATION_TREND_YEARS)))
    parser.add_argument("--recent-level-years", default=",".join(map(str, DEFAULT_RECENT_LEVEL_YEARS)))
    parser.add_argument("--age-share-years", default=",".join(map(str, DEFAULT_RECENT_LEVEL_YEARS)))
    parser.add_argument("--n-sim", type=int, default=3000)
    parser.add_argument("--random-seed", type=int, default=123)
    parser.add_argument(
        "--trend-damping",
        type=float,
        default=None,
        help=(
            "Backward-compatible shortcut. If supplied, it overrides both "
            "--immigration-trend-damping and --emigration-trend-damping."
        ),
    )
    parser.add_argument("--immigration-trend-damping", type=float, default=DEFAULT_IMMIGRATION_TREND_DAMPING)
    parser.add_argument("--emigration-trend-damping", type=float, default=DEFAULT_EMIGRATION_TREND_DAMPING)
    parser.add_argument("--immigration-slope-cap", type=float, default=DEFAULT_IMMIGRATION_SLOPE_CAP)
    parser.add_argument("--emigration-slope-cap", type=float, default=DEFAULT_EMIGRATION_SLOPE_CAP)
    parser.add_argument(
        "--single-age-method",
        choices=["smooth_rake", "band_rescaled"],
        default=DEFAULT_SINGLE_AGE_METHOD,
        help=(
            "smooth_rake is the default because it avoids artificial age-band boundary spikes while "
            "still preserving every broad age-band total exactly. band_rescaled reproduces the literal "
            "independent within-band Rogers-Castro allocation."
        ),
    )
    parser.add_argument(
        "--age-smoothing-iterations",
        type=int,
        default=DEFAULT_SMOOTHING_ITERATIONS,
        help="Number of smooth-and-rake iterations used when --single-age-method=smooth_rake.",
    )
    parser.add_argument(
        "--age-smoothing-strength",
        type=float,
        default=DEFAULT_SMOOTHING_STRENGTH,
        help="Blend weight for each smoothing pass. 0 keeps the literal band-rescaled curve; 1 uses the full smoothed pass.",
    )
    parser.add_argument(
        "--child-age-method",
        choices=["population_bridge", "population_only", "template_population"],
        default=DEFAULT_CHILD_AGE_METHOD,
        help=(
            "How to split and smooth the 0-17 broad age band. population_bridge starts from "
            "italiani.csv/stranieri.csv inside 0-17, then softly smooths across 17/18 while anchoring "
            "children back to that population profile. population_only keeps 0-17 exactly population-shaped "
            "and blocks smoothing across 17/18. template_population also multiplies children by the "
            "Rogers-Castro template, which can pull the child band toward age 17."
        ),
    )
    parser.add_argument(
        "--child-bridge-anchor",
        type=float,
        default=DEFAULT_CHILD_BRIDGE_ANCHOR,
        help=(
            "Only used with --child-age-method=population_bridge. Higher values keep 0-17 closer to the "
            "recent population profile; lower values smooth more strongly toward the young-adult migration peak."
        ),
    )
    args = parser.parse_args()

    outdir = resolve_output_path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    immigration_age_bands = read_flow_age_bands(args.immigration_input, "immigration")
    emigration_age_bands = read_flow_age_bands(args.emigration_input, "emigration")
    observed_age_bands = pd.concat([immigration_age_bands, emigration_age_bands], ignore_index=True)
    observed_totals = aggregate_observed_totals(observed_age_bands)

    immigration_trend_years = parse_year_list(args.immigration_trend_years, DEFAULT_IMMIGRATION_TREND_YEARS)
    emigration_trend_years = parse_year_list(args.emigration_trend_years, DEFAULT_EMIGRATION_TREND_YEARS)
    recent_level_years = parse_year_list(args.recent_level_years, DEFAULT_RECENT_LEVEL_YEARS)
    age_share_years = parse_year_list(args.age_share_years, DEFAULT_RECENT_LEVEL_YEARS)
    immigration_trend_damping = args.immigration_trend_damping if args.trend_damping is None else args.trend_damping
    emigration_trend_damping = args.emigration_trend_damping if args.trend_damping is None else args.trend_damping

    total_mean, total_intervals, total_sim, params = build_total_forecast(
        observed_totals,
        args.start_year,
        args.end_year,
        immigration_trend_years,
        emigration_trend_years,
        recent_level_years,
        args.n_sim,
        args.random_seed,
        immigration_trend_damping,
        emigration_trend_damping,
        args.immigration_slope_cap,
        args.emigration_slope_cap,
    )

    populations = pd.concat(
        [
            load_population(args.italian_population, "italiani"),
            load_population(args.foreign_population, "stranieri"),
        ],
        ignore_index=True,
    )
    templates = {
        "immigration": rogers_castro_template("immigration"),
        "emigration": rogers_castro_template("emigration"),
    }

    recent_shares = estimate_recent_component_shares(observed_age_bands, age_share_years)
    forecast_age_bands = make_forecast_age_bands(total_mean, recent_shares)
    forecast_single_age_components, expansion_diag_forecast = expand_age_bands_to_single_age(
        forecast_age_bands,
        populations,
        templates,
        single_age_method=args.single_age_method,
        smoothing_iterations=args.age_smoothing_iterations,
        smoothing_strength=args.age_smoothing_strength,
        child_age_method=args.child_age_method,
        child_bridge_anchor=args.child_bridge_anchor,
    )
    forecast_single_age_mean = append_net_single_age(forecast_single_age_components)
    forecast_age_bands_mean = append_net_age_bands(forecast_age_bands)

    observed_single_age, expansion_diag_observed = expand_age_bands_to_single_age(
        observed_age_bands,
        populations,
        templates,
        single_age_method=args.single_age_method,
        smoothing_iterations=args.age_smoothing_iterations,
        smoothing_strength=args.age_smoothing_strength,
        child_age_method=args.child_age_method,
        child_bridge_anchor=args.child_bridge_anchor,
    )
    observed_single_age = append_net_single_age(observed_single_age)
    observed_age_bands_with_net = append_net_age_bands(observed_age_bands)

    share_years = pd.DataFrame({"year": np.arange(args.start_year, args.end_year + 1)})
    age_band_shares_by_year = recent_shares.merge(share_years, how="cross")
    single_age_shares_by_year = make_single_age_flow_shares(
        age_band_shares_by_year,
        populations,
        templates,
        single_age_method=args.single_age_method,
        smoothing_iterations=args.age_smoothing_iterations,
        smoothing_strength=args.age_smoothing_strength,
        child_age_method=args.child_age_method,
        child_bridge_anchor=args.child_bridge_anchor,
    )
    single_age_intervals, age_band_intervals = summarize_age_sex_intervals(
        total_sim,
        single_age_shares_by_year,
        age_band_shares_by_year,
    )

    params["age_share_years_requested"] = ",".join(map(str, age_share_years))
    params["age_share_years_used"] = recent_shares["recent_years_used"].iloc[0]
    params["age_expansion_method"] = "recent_broad_age_shares_plus_rogers_castro_template_times_population_structure"
    params["single_age_method"] = args.single_age_method
    params["single_age_method_note"] = (
        "smooth_rake smooths across age-band boundaries and then rakes back to exact broad age-band totals; "
        "band_rescaled expands each age band independently and can create boundary spikes"
    )
    params["age_smoothing_iterations"] = args.age_smoothing_iterations
    params["age_smoothing_strength"] = args.age_smoothing_strength
    params["child_age_method"] = args.child_age_method
    params["child_bridge_anchor"] = args.child_bridge_anchor
    params["child_age_method_note"] = (
        "population_bridge starts from the relevant child population age-sex structure inside 0-17, "
        "then allows a soft bridge across 17/18 while anchoring children back to that initial profile; "
        "population_only keeps the child profile exact but can leave a 17/18 jump; "
        "template_population also applies the Rogers-Castro template inside 0-17"
    )
    params["origin_italia_population_structure"] = "italiani.csv"
    params["origin_paesi_esteri_population_structure"] = "stranieri.csv"
    params["output_dir"] = display_path(outdir)

    observed_age_bands.to_csv(outdir / "migration_observed_age_bands_by_origin_sex.csv", index=False)
    observed_age_bands_with_net.to_csv(outdir / "migration_observed_age_bands_with_net_by_origin_sex.csv", index=False)
    observed_totals.to_csv(outdir / "migration_observed_totals_by_year.csv", index=False)
    observed_single_age.to_csv(outdir / "migration_observed_single_age_reconstructed.csv", index=False)

    total_mean.to_csv(outdir / "migration_own_method_age_sex_forecast_mean.csv", index=False)
    total_intervals.to_csv(outdir / "migration_own_method_age_sex_forecast_intervals.csv", index=False)
    total_sim.to_csv(outdir / "migration_own_method_age_sex_forecast_simulations.csv", index=False)
    save_component_total_files(total_mean, total_intervals, outdir)

    recent_shares.to_csv(outdir / "migration_recent_component_age_band_shares.csv", index=False)
    forecast_age_bands_mean.to_csv(outdir / "migration_age_band_forecast_mean.csv", index=False)
    age_band_intervals.to_csv(outdir / "migration_age_band_forecast_intervals.csv", index=False)
    forecast_single_age_mean.to_csv(outdir / "migration_single_age_forecast_mean.csv", index=False)
    single_age_intervals.to_csv(outdir / "migration_single_age_forecast_intervals.csv", index=False)
    single_age_shares_by_year.to_csv(outdir / "migration_single_age_forecast_shares.csv", index=False)

    pd.concat(
        [
            expansion_diag_observed.assign(series_type="observed"),
            expansion_diag_forecast.assign(series_type="forecast_mean"),
        ],
        ignore_index=True,
    ).to_csv(outdir / "migration_age_range_expansion_diagnostics.csv", index=False)
    total_check(forecast_single_age_mean, total_mean).to_csv(outdir / "migration_single_age_total_preservation_check.csv", index=False)
    params.to_csv(outdir / "migration_own_method_age_sex_parameters.csv", index=False)

    print(f"Saved own-method age-sex migration outputs to: {display_path(outdir)}")
    print(params.to_string(index=False))


if __name__ == "__main__":
    main()
